added send message on enter option
signal-csharp/Signal-Windows pull request #224
Opened 2021-02-23 18:29 UTC by ShelbyBoss

Adds the option to disable sending message on enter. This makes it possible to for mobile users to add new lines.

I pretty much just copied the code of the spell check option.

2021-02-25 09:17 UTC, golf1052 requested changes

2021-02-25 09:17 UTC, golf1052 commented on Signal-Windows/Controls/Conversation.xaml.cs
> +            CoreWindow corWindow = CoreWindow.GetForCurrentThread();
```suggestion
            CoreWindow coreWindow = CoreWindow.GetForCurrentThread();
```

2021-02-25 09:17 UTC, golf1052 commented on Signal-Windows/Controls/Conversation.xaml.cs
> +            if (SendMessageWithEnterEnabled ? shift : !control)
On desktop if you change the setting after having opened a conversation this flag does not get updated on this page because the Conversation.xaml does not get loaded again. I recommend just referring to the setting directly.

```suggestion
            if (GlobalSettingsManager.SendMessageWithEnterSetting ? shift : !control)
```

2021-02-25 09:17 UTC, golf1052 commented on Signal-Windows/Controls/Conversation.xaml.cs
> +        }
This isn't necessary because we don't use this property in the .xaml.

2021-02-25 17:31 UTC, ShelbyBoss commented
I removed the proptery SendMessageWithEnterEnabled and fixed the typo.

2021-02-26 00:58 UTC, golf1052 approved these changes

2021-02-26 00:58 UTC, merged

2021-02-26 00:58 UTC, golf1052 commented
Thanks for the PR!